#!/bin/bash

# Build libgit2 using openssl 1.1.1d and libssh 1.9.0
# Place results in libgit2-1.0.1-catalyst

set -e

# source the common build functions
SCRIPT_DIR=$(dirname "$0")
source "${SCRIPT_DIR}/ios_build_functions.sh"

function setup ()
{
    if [ -f "${ROOT_PATH}/External/libgit2-1.0.1-catalyst/libgit2-1.0.1-catalyst.a" ] && [ "${ROOT_PATH}/External/libgit2-1.0.1-catalyst/libgit2-1.0.1-catalyst.a" -nt "${ROOT_PATH}/External/libgit2-1.0.1" ]
    then
        echo "No update needed."
        exit 0
    fi

    LIBRARY_NAME="libgit2"
    LIB_PATH="${ROOT_PATH}/External/libgit2-1.0.1-catalyst"
    rm -rf "${LIB_PATH}"

    pushd "${ROOT_PATH}/External/libgit2-1.0.1" > /dev/null
}

function build_libgit2 ()
{
    rm -rf "build"
    mkdir "build"

    pushd "build" > /dev/null

    # install the each built arch somewhere sane
    INSTALL_PREFIX="${LIB_PATH}/${SDKNAME}-${ARCH}.sdk"

    mkdir -p "${INSTALL_PREFIX}"

    LOG="${INSTALL_PREFIX}/build-libgit2.log"
    echo "$LOG"
    echo "Build date: $(DATE)" >> "${LOG}" 2>&1
    
    cmake \
        -DCMAKE_C_COMPILER_WORKS:BOOL=ON \
        -DBUILD_SHARED_LIBS:BOOL=OFF \
        -DCMAKE_PREFIX_PATH:PATH="${ROOT_PATH}/External/libssh-1.0.9-catalyst/bin/${SDKNAME}-${ARCH}.sdk" \
        -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH:BOOL=ON \
        -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_PREFIX}/" \
        -DBUILD_CLAR:BOOL=OFF \
        -DTHREADSAFE:BOOL=ON \
        -DCURL:BOOL=OFF \
        -DCMAKE_C_FLAGS:STRING="-fembed-bitcode --target=arm64-apple-ios13.0-macabi" \
        "${SYS_ROOT}" \
        -DCMAKE_OSX_ARCHITECTURES:STRING="${ARCH}" \
        .. >> "${LOG}" 2>&1
    cmake --build . --target install >> "${LOG}" 2>&1

    # push the built library into the list
    BUILT_LIB_PATHS+=("${INSTALL_PREFIX}/lib/libgit2.a")
    popd > /dev/null
}

function fat_binary ()
{
    echo "Building fat binary..."

    lipo -create "${BUILT_LIB_PATHS[@]}" -output "${ROOT_PATH}/External/libgit2-1.0.1-catalyst/libgit2-1.0.1-catalyst.a"

    echo "Building done."

    popd > /dev/null
}

build_catalyst setup build_libgit2 fat_binary
